"""
WMO SYNOP station configuration (data_source = 'SYNOP_GTS').

Auto-generated 2026-06-17 from NOAA isd-history.csv + GHCNh/GHCN-Daily
inventories, coord-validated (see NOAA_NCEI_INGESTION_SCOPE.md §2e).
ADDITIVE layer — never replaces council Hilltop / Harvest devices.

Per station:
  wmo_block   : live key (Ogimet/Unidata SYNOP).
  ghcnh_id    : NOAA GHCN-hourly id (reconciliation + hourly backfill); may be None.
  ghcnd_id    : NOAA GHCN-Daily id (daily backfill); often None (sparse / id drift).
  zone_slug   : wine climate_zones.slug if in/adjacent a wine zone, else None.
  region      : wine region label, or None if not in a wine zone.
  contributes_to_regional : True only when zone_slug is set.
"""

SYNOP_SITES = {
    'SYNOP_93110': {
        'wmo_block': '93110',
        'name': "Auckland Aero Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093110',
        'ghcnd_id': 'NZM00093110',
        'lat': -37.0,
        'lon': 174.8,
        'elevation': 7.0,
        'zone_slug': 'auckland',
        'region': 'Auckland',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93119': {
        'wmo_block': '93119',
        'name': "Auckland Intl",
        'icao': 'NZAA',
        'ghcnh_id': 'NZI0000NZAA',
        'ghcnd_id': None,
        'lat': -37.008,
        'lon': 174.792,
        'elevation': 7.0,
        'zone_slug': 'auckland',
        'region': 'Auckland',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93597': {
        'wmo_block': '93597',
        'name': "Cape Campbell Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093597',
        'ghcnd_id': None,
        'lat': -41.717,
        'lon': 174.267,
        'elevation': 32.0,
        'zone_slug': 'awatere',
        'region': 'Marlborough',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93498': {
        'wmo_block': '93498',
        'name': "Castlepoint",
        'icao': None,
        'ghcnh_id': 'NZM00093498',
        'ghcnd_id': None,
        'lat': -40.9,
        'lon': 176.2,
        'elevation': 120.0,
        'zone_slug': 'wairarapa',
        'region': 'Wairarapa',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93781': {
        'wmo_block': '93781',
        'name': "Christchurch Aero Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093781',
        'ghcnd_id': 'NZM00093781',
        'lat': -43.483,
        'lon': 172.517,
        'elevation': 37.0,
        'zone_slug': 'north-canterbury',
        'region': 'North Canterbury',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93780': {
        'wmo_block': '93780',
        'name': "Christchurch Intl",
        'icao': 'NZCH',
        'ghcnh_id': 'NZI0000NZCH',
        'ghcnd_id': None,
        'lat': -43.489,
        'lon': 172.532,
        'elevation': 37.5,
        'zone_slug': 'north-canterbury',
        'region': 'North Canterbury',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93527': {
        'wmo_block': '93527',
        'name': "Farewell Spit Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093527',
        'ghcnd_id': None,
        'lat': -40.55,
        'lon': 173.0,
        'elevation': 3.0,
        'zone_slug': 'nelson',
        'region': 'Nelson',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93292': {
        'wmo_block': '93292',
        'name': "Gisborne",
        'icao': 'NZGS',
        'ghcnh_id': 'NZI0000NZGS',
        'ghcnd_id': 'NZ000093292',
        'lat': -38.663,
        'lon': 177.978,
        'elevation': 4.6,
        'zone_slug': 'gisborne',
        'region': 'Gisborne',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93021': {
        'wmo_block': '93021',
        'name': "Kerikeri Aero Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093021',
        'ghcnd_id': None,
        'lat': -35.25,
        'lon': 173.9,
        'elevation': 151.0,
        'zone_slug': 'northland',
        'region': 'Northland',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93393': {
        'wmo_block': '93393',
        'name': "Mahia Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093393',
        'ghcnd_id': None,
        'lat': -39.117,
        'lon': 177.95,
        'elevation': 136.0,
        'zone_slug': 'gisborne',
        'region': 'Gisborne',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93373': {
        'wmo_block': '93373',
        'name': "Napier Aerodrome Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093373',
        'ghcnd_id': None,
        'lat': -39.467,
        'lon': 176.867,
        'elevation': 3.0,
        'zone_slug': 'hawkes-bay',
        'region': "Hawke's Bay",
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93546': {
        'wmo_block': '93546',
        'name': "Nelson Aerodrome Aws",
        'icao': 'NZNS',
        'ghcnh_id': 'NZM00093546',
        'ghcnd_id': None,
        'lat': -41.3,
        'lon': 173.2,
        'elevation': 6.0,
        'zone_slug': 'nelson',
        'region': 'Nelson',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93479': {
        'wmo_block': '93479',
        'name': "Ngawi",
        'icao': None,
        'ghcnh_id': 'NZM00093479',
        'ghcnd_id': None,
        'lat': -41.583,
        'lon': 175.233,
        'elevation': 8.0,
        'zone_slug': 'martinborough',
        'region': 'Wairarapa',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93796': {
        'wmo_block': '93796',
        'name': "Oamaru Airport Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093796',
        'ghcnd_id': None,
        'lat': -44.967,
        'lon': 171.083,
        'elevation': 31.0,
        'zone_slug': 'waitaki',
        'region': 'Waitaki',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93831': {
        'wmo_block': '93831',
        'name': "Queenstown Aerodrome",
        'icao': None,
        'ghcnh_id': 'NZM00093831',
        'ghcnd_id': None,
        'lat': -45.017,
        'lon': 168.733,
        'elevation': 358.0,
        'zone_slug': 'gibbston',
        'region': 'Central Otago',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93562': {
        'wmo_block': '93562',
        'name': "Stephens Island Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093562',
        'ghcnd_id': None,
        'lat': -40.65,
        'lon': 173.983,
        'elevation': 180.0,
        'zone_slug': 'marlborough',
        'region': 'Marlborough',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93441': {
        'wmo_block': '93441',
        'name': "Takapau Plains Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093441',
        'ghcnd_id': None,
        'lat': -40.033,
        'lon': 176.267,
        'elevation': 330.0,
        'zone_slug': 'hawkes-bay',
        'region': "Hawke's Bay",
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93747': {
        'wmo_block': '93747',
        'name': "Tara Hills",
        'icao': None,
        'ghcnh_id': 'NZM00093747',
        'ghcnd_id': 'NZ000937470',
        'lat': -44.517,
        'lon': 169.9,
        'elevation': 488.0,
        'zone_slug': 'waitaki',
        'region': 'Waitaki',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93057': {
        'wmo_block': '93057',
        'name': "Whangarei Aerodrome",
        'icao': None,
        'ghcnh_id': 'NZM00093057',
        'ghcnd_id': None,
        'lat': -35.767,
        'lon': 174.367,
        'elevation': 38.0,
        'zone_slug': 'northland',
        'region': 'Northland',
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': True,
    },
    'SYNOP_93947': {
        'wmo_block': '93947',
        'name': "Cambell Island Aws",
        'icao': None,
        'ghcnh_id': None,
        'ghcnd_id': None,
        'lat': -52.55,
        'lon': 169.15,
        'elevation': 19.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93004': {
        'wmo_block': '93004',
        'name': "Cape Reinga Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093004',
        'ghcnd_id': None,
        'lat': -34.433,
        'lon': 172.683,
        'elevation': 216.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93985': {
        'wmo_block': '93985',
        'name': "Chatham Island Aerodrome Aws",
        'icao': None,
        'ghcnh_id': None,
        'ghcnd_id': None,
        'lat': -43.817,
        'lon': -176.483,
        'elevation': 13.1,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93891': {
        'wmo_block': '93891',
        'name': "Dunedin Aerodrome Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093891',
        'ghcnd_id': None,
        'lat': -45.917,
        'lon': 170.183,
        'elevation': 2.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93929': {
        'wmo_block': '93929',
        'name': "Enderby Island Aws",
        'icao': None,
        'ghcnh_id': None,
        'ghcnd_id': None,
        'lat': -50.483,
        'lon': 166.3,
        'elevation': 40.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93708': {
        'wmo_block': '93708',
        'name': "Haast",
        'icao': 'NZHT',
        'ghcnh_id': 'NZI0000NZHT',
        'ghcnd_id': None,
        'lat': -43.867,
        'lon': 169.0,
        'elevation': 4.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93173': {
        'wmo_block': '93173',
        'name': "Hamilton Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093173',
        'ghcnd_id': None,
        'lat': -37.85,
        'lon': 175.333,
        'elevation': 53.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93313': {
        'wmo_block': '93313',
        'name': "Hawera Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093313',
        'ghcnd_id': None,
        'lat': -39.6,
        'lon': 174.283,
        'elevation': 100.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93196': {
        'wmo_block': '93196',
        'name': "Hicks Bay Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093196',
        'ghcnd_id': None,
        'lat': -37.55,
        'lon': 178.3,
        'elevation': 46.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93614': {
        'wmo_block': '93614',
        'name': "Hokitika Aerodrome",
        'icao': None,
        'ghcnh_id': None,
        'ghcnd_id': None,
        'lat': -42.717,
        'lon': 170.983,
        'elevation': 44.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93845': {
        'wmo_block': '93845',
        'name': "Invercargill Airport Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093845',
        'ghcnd_id': None,
        'lat': -46.417,
        'lon': 168.333,
        'elevation': 2.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93678': {
        'wmo_block': '93678',
        'name': "Kaikoura",
        'icao': None,
        'ghcnh_id': None,
        'ghcnd_id': 'NZM00093678',
        'lat': -42.417,
        'lon': 173.7,
        'elevation': 101.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93792': {
        'wmo_block': '93792',
        'name': "Le Bon Bay Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093792',
        'ghcnd_id': None,
        'lat': -43.733,
        'lon': 173.117,
        'elevation': 238.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93721': {
        'wmo_block': '93721',
        'name': "Milford Soundn Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093721',
        'ghcnd_id': None,
        'lat': -44.667,
        'lon': 167.917,
        'elevation': 6.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93069': {
        'wmo_block': '93069',
        'name': "Mokohinau Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093069',
        'ghcnd_id': None,
        'lat': -35.9,
        'lon': 175.1,
        'elevation': 60.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93738': {
        'wmo_block': '93738',
        'name': "Mt Cook Aerodrome Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093738',
        'ghcnd_id': None,
        'lat': -43.767,
        'lon': 170.133,
        'elevation': 656.2,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93309': {
        'wmo_block': '93309',
        'name': "New Plymouth Aws",
        'icao': None,
        'ghcnh_id': None,
        'ghcnd_id': 'NZ000933090',
        'lat': -39.017,
        'lon': 174.183,
        'elevation': 32.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93887': {
        'wmo_block': '93887',
        'name': "Nugget Point Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093887',
        'ghcnd_id': None,
        'lat': -46.45,
        'lon': 169.817,
        'elevation': 130.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93404': {
        'wmo_block': '93404',
        'name': "Palmerston North Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093404',
        'ghcnd_id': None,
        'lat': -40.317,
        'lon': 175.6,
        'elevation': 39.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93420': {
        'wmo_block': '93420',
        'name': "Paraparaumu Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093420',
        'ghcnd_id': None,
        'lat': -40.9,
        'lon': 174.983,
        'elevation': 7.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93201': {
        'wmo_block': '93201',
        'name': "Port Taharoa",
        'icao': None,
        'ghcnh_id': 'NZM00093201',
        'ghcnd_id': None,
        'lat': -38.167,
        'lon': 174.7,
        'elevation': 28.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93805': {
        'wmo_block': '93805',
        'name': "Puysegur Point Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093805',
        'ghcnd_id': None,
        'lat': -46.15,
        'lon': 166.6,
        'elevation': 44.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93167': {
        'wmo_block': '93167',
        'name': "Raglan",
        'icao': None,
        'ghcnh_id': 'NZM00093167',
        'ghcnd_id': None,
        'lat': -37.8,
        'lon': 174.85,
        'elevation': 12.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93994': {
        'wmo_block': '93994',
        'name': "Raoul Island Aws",
        'icao': None,
        'ghcnh_id': None,
        'ghcnd_id': None,
        'lat': -29.25,
        'lon': -177.933,
        'elevation': 49.5,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93800': {
        'wmo_block': '93800',
        'name': "Secretary Island Aws",
        'icao': None,
        'ghcnh_id': None,
        'ghcnd_id': None,
        'lat': -45.217,
        'lon': 166.883,
        'elevation': 19.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93909': {
        'wmo_block': '93909',
        'name': "South West Cape Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093909',
        'ghcnd_id': None,
        'lat': -47.267,
        'lon': 167.45,
        'elevation': 102.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93245': {
        'wmo_block': '93245',
        'name': "Taupo Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093245',
        'ghcnd_id': None,
        'lat': -38.733,
        'lon': 176.067,
        'elevation': 401.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93186': {
        'wmo_block': '93186',
        'name': "Tauranga",
        'icao': 'NZTG',
        'ghcnh_id': 'NZI0000NZTG',
        'ghcnd_id': None,
        'lat': -37.672,
        'lon': 176.196,
        'elevation': 4.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93773': {
        'wmo_block': '93773',
        'name': "Timaru Aerodrome Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093773',
        'ghcnd_id': None,
        'lat': -44.3,
        'lon': 171.233,
        'elevation': 27.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93339': {
        'wmo_block': '93339',
        'name': "Waiouru Airstrip",
        'icao': None,
        'ghcnh_id': 'NZM00093339',
        'ghcnd_id': None,
        'lat': -39.433,
        'lon': 175.65,
        'elevation': 819.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93439': {
        'wmo_block': '93439',
        'name': "Wellington Aero Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093439',
        'ghcnd_id': 'NZM00093439',
        'lat': -41.333,
        'lon': 174.8,
        'elevation': 12.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93436': {
        'wmo_block': '93436',
        'name': "Wellington Intl",
        'icao': 'NZWN',
        'ghcnh_id': 'NZI0000NZWN',
        'ghcnd_id': None,
        'lat': -41.3,
        'lon': 174.8,
        'elevation': 7.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93515': {
        'wmo_block': '93515',
        'name': "Westport Aerodrome",
        'icao': None,
        'ghcnh_id': 'NZM00093515',
        'ghcnd_id': None,
        'lat': -41.733,
        'lon': 171.567,
        'elevation': 5.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93191': {
        'wmo_block': '93191',
        'name': "Whakatane Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093191',
        'ghcnd_id': None,
        'lat': -37.917,
        'lon': 176.917,
        'elevation': 7.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
    'SYNOP_93129': {
        'wmo_block': '93129',
        'name': "Whitianga Aerodrome Aws",
        'icao': None,
        'ghcnh_id': 'NZM00093129',
        'ghcnd_id': None,
        'lat': -36.867,
        'lon': 175.667,
        'elevation': 6.0,
        'zone_slug': None,
        'region': None,
        'measurements': ['temp', 'dewpoint', 'rh', 'pressure', 'pressure_msl', 'wind_speed', 'wind_direction', 'rainfall'],
        'contributes_to_regional': False,
    },
}

# Live transport: Unidata IDD/LDM in prod; Ogimet getsynop (recent ~4mo) for dev.
OGIMET_GETSYNOP = 'https://www.ogimet.com/cgi-bin/getsynop'
