"""add_spatial_support_to_blocks

Revision ID: 848feb1504bd
Revises: fad21e424370
Create Date: 2025-05-03 21:55:17.178409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '848feb1504bd'
down_revision: Union[str, None] = 'fad21e424370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vineyard_blocks', 'block_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('vineyard_blocks', 'row_spacing',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('vineyard_blocks', 'vine_spacing',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('vineyard_blocks', 'area',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('vineyard_blocks', 'centroid_longitude',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('vineyard_blocks', 'centroid_latitude',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('vineyard_blocks', 'elevation',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('vineyard_blocks', 'geometry',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vineyard_blocks', 'geometry',
               existing_type=geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
    op.alter_column('vineyard_blocks', 'elevation',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=True)
    op.alter_column('vineyard_blocks', 'centroid_latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('vineyard_blocks', 'centroid_longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('vineyard_blocks', 'area',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('vineyard_blocks', 'vine_spacing',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('vineyard_blocks', 'row_spacing',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('vineyard_blocks', 'block_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
