"""Drop the observation_plans layer entirely.

The 2026-05-29 batch collapsed the two-layer Plan + Run model into a single
Run-as-the-work-unit. Plans were kept in DB as a fallback after that ship
in case the new flow had a sharp edge; field testing was clean so they go
now.

All data that mattered was already mirrored onto observation_runs by the
`add_run_scheduling_fields` migration (scheduled_date, assigned_to_user_id,
instructions). Plan names were already copied into run.name at creation
time. Nothing else on a plan was load-bearing.

Order matters:
  1. Drop the FK from observation_runs.plan_id (catalog lookup so we don't
     hardcode an autogenerated constraint name)
  2. Drop the plan_id column
  3. Drop the three plan tables (assignees + targets before plans because
     of their FK back to plans — explicit DROP CASCADE on plans would also
     do it but being explicit is clearer)

Downgrade recreates the tables + plan_id column (no data restoration —
plans are not coming back).

Revision ID: drop_observation_plans
Revises: add_run_scheduling_fields
Create Date: 2026-05-29
"""
from alembic import op
import sqlalchemy as sa


revision = 'drop_observation_plans'
down_revision = 'add_run_scheduling_fields'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Drop FK from observation_runs.plan_id by catalog lookup
    op.execute("""
        DO $$
        DECLARE r record;
        BEGIN
            FOR r IN SELECT conname FROM pg_constraint
                     WHERE conrelid = 'observation_runs'::regclass
                       AND contype = 'f'
                       AND confrelid = 'observation_plans'::regclass
            LOOP
                EXECUTE 'ALTER TABLE observation_runs DROP CONSTRAINT ' || quote_ident(r.conname);
            END LOOP;
        END $$;
    """)

    # 2. Drop plan_id column
    op.drop_column('observation_runs', 'plan_id')

    # 3. Drop the three plan tables (children first, parent last)
    op.drop_table('observation_plan_assignees')
    op.drop_table('observation_plan_targets')
    op.drop_table('observation_plans')


def downgrade():
    # Recreate skeleton schema — does NOT restore data.
    op.create_table(
        'observation_plans',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('company_id', sa.Integer(),
                  sa.ForeignKey('companies.id', ondelete='CASCADE'),
                  nullable=False),
        sa.Column('template_id', sa.Integer(),
                  sa.ForeignKey('observation_templates.id'),
                  nullable=False),
        sa.Column('template_version', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(160), nullable=False),
        sa.Column('instructions', sa.Text(), nullable=True),
        sa.Column('due_start_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('due_end_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('rrule', sa.Text(), nullable=True),
        sa.Column('priority', sa.String(20), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, server_default='scheduled'),
        sa.Column('created_by', sa.Integer(),
                  sa.ForeignKey('users.id'),
                  nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True),
                  server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True),
                  server_default=sa.func.now(),
                  onupdate=sa.func.now()),
    )

    op.create_table(
        'observation_plan_targets',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('plan_id', sa.Integer(),
                  sa.ForeignKey('observation_plans.id', ondelete='CASCADE'),
                  nullable=False),
        sa.Column('block_id', sa.Integer(),
                  sa.ForeignKey('vineyard_blocks.id', ondelete='CASCADE'),
                  nullable=False),
        sa.Column('row_labels', sa.JSON(), nullable=False, server_default='[]'),
        sa.Column('asset_id', sa.Integer(),
                  sa.ForeignKey('assets.id'),
                  nullable=True),
        sa.Column('sample_size', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
    )

    op.create_table(
        'observation_plan_assignees',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('plan_id', sa.Integer(),
                  sa.ForeignKey('observation_plans.id', ondelete='CASCADE'),
                  nullable=False),
        sa.Column('user_id', sa.Integer(),
                  sa.ForeignKey('users.id'),
                  nullable=False),
    )

    op.add_column(
        'observation_runs',
        sa.Column('plan_id', sa.Integer(),
                  sa.ForeignKey('observation_plans.id'),
                  nullable=True),
    )
