"""Make contractor_assignments.task_id FK ON DELETE SET NULL.

Before: bare FK with NO ACTION (PG default). A task that had any contractor
assignment couldn't be hard-deleted at all without raising — yet Pete saw
deleted-task orphans in the mobile contractor task list, suggesting the FK
isn't actually being enforced on prod (likely created without a name + lost
during one of the earlier model refactors).

After: deleting a task nulls out the FK on any assignment that referenced
it, leaving the assignment as a generic-work record (still useful for the
contractor's own history) instead of orphaning or hard-blocking. The
mobile /me/assignments orphan filter (added in the same batch) keeps the
list clean by hiding rows where task_id is set but the task is missing —
this migration covers future deletes cleanly.

Catalog-aware drop so we don't have to know the autogenerated constraint
name; recreates with an explicit name so future migrations don't have to
re-do the lookup dance.

Revision ID: set_assignment_task_setnull
Revises: drop_observation_plans
Create Date: 2026-05-29
"""
from alembic import op
import sqlalchemy as sa


revision = 'set_assignment_task_setnull'
down_revision = 'drop_observation_plans'
branch_labels = None
depends_on = None


def upgrade():
    # Drop whatever FK currently links contractor_assignments.task_id → tasks.id
    op.execute("""
        DO $$
        DECLARE r record;
        BEGIN
            FOR r IN SELECT conname FROM pg_constraint
                     WHERE conrelid = 'contractor_assignments'::regclass
                       AND contype = 'f'
                       AND confrelid = 'tasks'::regclass
            LOOP
                EXECUTE 'ALTER TABLE contractor_assignments DROP CONSTRAINT ' || quote_ident(r.conname);
            END LOOP;
        END $$;
    """)

    # Clean orphan task_id values created while no FK was being enforced
    # (or while the FK didn't exist). Without this, the new SET NULL FK can't
    # be validated against existing data. Effectively converts orphan rows to
    # generic-work assignments — matches the ON DELETE SET NULL behaviour
    # we're about to install.
    op.execute("""
        UPDATE contractor_assignments
        SET task_id = NULL
        WHERE task_id IS NOT NULL
          AND task_id NOT IN (SELECT id FROM tasks);
    """)

    # Recreate with explicit name + ON DELETE SET NULL
    op.create_foreign_key(
        'fk_contractor_assignments_task_id_set_null',
        source_table='contractor_assignments',
        referent_table='tasks',
        local_cols=['task_id'],
        remote_cols=['id'],
        ondelete='SET NULL',
    )


def downgrade():
    op.drop_constraint(
        'fk_contractor_assignments_task_id_set_null',
        'contractor_assignments',
        type_='foreignkey',
    )
    # Restore plain FK (no cascade rule) — matches pre-migration behaviour.
    op.create_foreign_key(
        None,
        source_table='contractor_assignments',
        referent_table='tasks',
        local_cols=['task_id'],
        remote_cols=['id'],
    )
