"""Create surface_run and surface_validation_stats — the climate surface index.

SURFACE_CONTRACT_V2 §3, as amended 2026-08-13 (§8.2). The rasters live on S3;
Postgres holds only the index and the statistics, so one SQL query locates any
surface and reports how accurate it is. Nothing here stores pixels.

Two shapes in the contract needed care, and both are why this is hand-written
rather than autogenerated:

1. `statistic` is NULL for daily/hourly surfaces and required for
   monthly/records. Postgres treats NULLs as DISTINCT in a unique index, so a
   single unique constraint over a nullable `statistic` would happily accept the
   same daily surface a hundred times without collision. Hence two PARTIAL
   unique indexes — one `WHERE statistic IS NULL`, one `WHERE statistic IS NOT
   NULL`. The alternative, storing '' for per-timestep rows, invites a consumer
   to treat empty string as a statistic name.

2. `surface_validation_stats` is keyed on the FIT, not on the raster, and has NO
   FK to surface_run. One month of temp_min is ~14 rasters (one per statistic)
   produced from ~30 daily fits, so a per-raster FK is wrong at both ends: it
   duplicates identical statistics 14x and has no single row to point at. The
   grain is (variable, valid_on, resolution_m, model_version) — exactly the
   13,878 rows per variable that run_history.py already emits to
   validation_stats.csv.

Volume note: the 1986-2023 recompute is ~4,560 monthly rasters per variable, so
surface_run reaches ~14k rows for the three temperature variables and
surface_validation_stats ~42k. Both are trivially small; the indexes here are
for query shape, not for scale.

Revision ID: surface_index_tables
Revises: task_parent_fk
Create Date: 2026-08-13
"""
from alembic import op
import sqlalchemy as sa

revision = 'surface_index_tables'
down_revision = 'task_parent_fk'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'surface_run',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),

        sa.Column('variable', sa.Text(), nullable=False),
        sa.Column('granularity', sa.Text(), nullable=False),
        # NULL for daily/hourly, required for monthly/records. See note 1.
        sa.Column('statistic', sa.Text(), nullable=True),

        # daily -> midnight UTC; monthly -> first instant of the month;
        # records -> the END of the covered period.
        sa.Column('valid_at', sa.DateTime(timezone=True), nullable=False),
        # Only set for `records`. An all-time surface covers a span, and without
        # both bounds "all-time" silently changes meaning each time the archive
        # is extended.
        sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),

        sa.Column('resolution_m', sa.Integer(), nullable=False),
        sa.Column('model_version', sa.Text(), nullable=False),
        sa.Column('engine', sa.Text(), nullable=True),

        sa.Column('s3_key', sa.Text(), nullable=False),
        sa.Column('s3_key_sd', sa.Text(), nullable=True),

        sa.Column('n_stations_fit', sa.Integer(), nullable=True),
        sa.Column('n_stations_test', sa.Integer(), nullable=True),
        sa.Column('n_stations_excluded', sa.Integer(), nullable=True),
        sa.Column('relevance_km', sa.Float(precision=53), nullable=True),

        sa.Column('smoothing', sa.Float(precision=53), nullable=True),
        sa.Column('edf', sa.Float(precision=53), nullable=True),
        sa.Column('edf_frac', sa.Float(precision=53), nullable=True),

        # Summary of the fits behind this object, so /point and /available
        # answer from one row without a join. For daily the two agree; for
        # monthly they do not, and the max is the honest one to show beside a
        # monthly extreme.
        sa.Column('cv_rmse', sa.Float(precision=53), nullable=True),
        sa.Column('cv_rmse_max', sa.Float(precision=53), nullable=True),

        sa.Column('clipped', sa.Boolean(), nullable=True),
        sa.Column('status', sa.Text(), nullable=False, server_default='ok'),
        sa.Column('created_at', sa.DateTime(timezone=True),
                  server_default=sa.text('now()'), nullable=False),

        sa.PrimaryKeyConstraint('id'),
        # 'degraded' is served WITH its confidence rather than hidden — the
        # contract is explicit that a poor surface honestly labelled beats a
        # missing one.
        sa.CheckConstraint(
            "status IN ('ok', 'degraded', 'failed')",
            name='ck_surface_run_status'),
        sa.CheckConstraint(
            "granularity IN ('daily', 'hourly', 'monthly', 'records')",
            name='ck_surface_run_granularity'),
        # The contract's rule, enforced rather than documented: a statistic on a
        # per-timestep surface is meaningless, and its absence on an aggregate
        # makes the row unidentifiable.
        sa.CheckConstraint(
            "(granularity IN ('daily', 'hourly') AND statistic IS NULL) OR "
            "(granularity IN ('monthly', 'records') AND statistic IS NOT NULL)",
            name='ck_surface_run_statistic_by_granularity'),
        sa.CheckConstraint(
            "(granularity = 'records') = (period_start IS NOT NULL)",
            name='ck_surface_run_period_start'),
    )

    # Two partial unique indexes rather than one constraint. See note 1.
    op.create_index(
        'uq_surface_run_timestep', 'surface_run',
        ['variable', 'granularity', 'valid_at', 'resolution_m', 'model_version'],
        unique=True, postgresql_where=sa.text('statistic IS NULL'))
    op.create_index(
        'uq_surface_run_aggregate', 'surface_run',
        ['variable', 'granularity', 'statistic', 'valid_at', 'resolution_m',
         'model_version'],
        unique=True, postgresql_where=sa.text('statistic IS NOT NULL'))

    # The read path: "give me this variable over this window", which is what
    # /point, /region and /available all reduce to.
    op.create_index(
        'ix_surface_run_lookup', 'surface_run',
        ['variable', 'granularity', 'valid_at'])
    op.create_index('ix_surface_run_s3_key', 'surface_run', ['s3_key'])

    op.create_table(
        'surface_validation_stats',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),

        # Grain = one fit. Deliberately NOT an FK to surface_run. See note 2.
        sa.Column('variable', sa.Text(), nullable=False),
        sa.Column('valid_on', sa.Date(), nullable=False),
        sa.Column('resolution_m', sa.Integer(), nullable=False),
        sa.Column('model_version', sa.Text(), nullable=False),

        sa.Column('n_fit', sa.Integer(), nullable=True),
        sa.Column('n_test', sa.Integer(), nullable=True),

        # THE published number: shuffled 10-fold CV, lambda re-selected inside
        # each fold, with production's clip applied. Contract §3.3.
        sa.Column('cv_rmse', sa.Float(precision=53), nullable=True),
        # In-sample residual. NEVER publish it — it measures how hard the
        # surface smoothed, not how right it is.
        sa.Column('rmse', sa.Float(precision=53), nullable=True),
        # Declustered holdout; only meaningful at n_test >= 10.
        sa.Column('t_rmse', sa.Float(precision=53), nullable=True),
        # Retained for schema stability only. mean(y)/rmse is origin-dependent —
        # the same surface in Kelvin scores ~15x higher. Use edf_frac instead.
        sa.Column('snr', sa.Float(precision=53), nullable=True),
        sa.Column('mae', sa.Float(precision=53), nullable=True),
        sa.Column('bias', sa.Float(precision=53), nullable=True),
        sa.Column('r2', sa.Float(precision=53), nullable=True),
        sa.Column('max_abs_error', sa.Float(precision=53), nullable=True),

        sa.Column('edf', sa.Float(precision=53), nullable=True),
        sa.Column('lam', sa.Float(precision=53), nullable=True),

        sa.Column('created_at', sa.DateTime(timezone=True),
                  server_default=sa.text('now()'), nullable=False),

        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('variable', 'valid_on', 'resolution_m',
                            'model_version', name='uq_surface_validation_fit'),
    )

    op.create_index(
        'ix_surface_validation_lookup', 'surface_validation_stats',
        ['variable', 'valid_on'])


def downgrade():
    op.drop_index('ix_surface_validation_lookup', table_name='surface_validation_stats')
    op.drop_table('surface_validation_stats')
    op.drop_index('ix_surface_run_s3_key', table_name='surface_run')
    op.drop_index('ix_surface_run_lookup', table_name='surface_run')
    op.drop_index('uq_surface_run_aggregate', table_name='surface_run')
    op.drop_index('uq_surface_run_timestep', table_name='surface_run')
    op.drop_table('surface_run')
